// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3-5hPqK1UNngEe-loWmjXQXDnxhQdT7w',
    appId: '1:169014988560:web:ea38bf4d58f46189545f95',
    messagingSenderId: '169014988560',
    projectId: 'task-admin-7be7d',
    authDomain: 'task-admin-7be7d.firebaseapp.com',
    databaseURL: 'https://task-admin-7be7d-default-rtdb.firebaseio.com',
    storageBucket: 'task-admin-7be7d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYdzqX3rDjck7jU6QDcjn2OZfUhXFy2WU',
    appId: '1:169014988560:android:1fce870076d312c0545f95',
    messagingSenderId: '169014988560',
    projectId: 'task-admin-7be7d',
    databaseURL: 'https://task-admin-7be7d-default-rtdb.firebaseio.com',
    storageBucket: 'task-admin-7be7d.appspot.com',
  );
}
